version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    privileged: true
    build: .
    volumes:
      - ./src:/app
      - ./data/web:/data
    environment:
      TZ: "Europe/Helsinki"
    ports:
      - "8000:8000"
    depends_on:
      - db
