version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: ./src/web
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    volumes:
      - ./src/web:/web
      - ./data/web:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
