# Generated by Django 2.2.2 on 2019-06-29 14:35

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wishlist.Holder')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('url', models.URLField(blank=True)),
                ('platforms', models.ManyToManyField(to='wishlist.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', positions.fields.PositionField(default=-1)),
                ('url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wishlist.Series')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wishlist.Store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wishlist.Type')),
            ],
        ),
    ]
