# Generated by Django 2.2.3 on 2019-07-04 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('preset', models.FileField(upload_to='encoding/type/presets/', validators=[django.core.validators.FileExtensionValidator(['json'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='encoding/job/files/', validators=[django.core.validators.FileExtensionValidator(['mkv'])])),
                ('output', models.CharField(blank=True, max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Encoding'), (2, 'Done')], default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encoding.Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
