# Generated by Django 2.2.3 on 2019-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_output_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
